### ISSUE TITLE
[FEATURE] Add Blogs page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#11]
### Detailed description

We have to build a page like this(excluding hamburger icon)
<img alt="drawing" width="200" src="https://user-images.githubusercontent.com/44284877/194080149-5663d26e-9a56-495e-ada1-b83494d877ad.png">

### Context

Website: https://www.thecyberhub.org/blogs
React Sourcecode: https://github.com/thecyberworld/thecyberhub.org

### Possible implementation

If you need any help or have any doubts, let us know below.

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stringsaeed** [comment]
Hello @kabir0x23 can you assign me the issue, I will be working on it

**Comment by kabir0x23** [comment]
> Hello @kabir0x23 can you assign me the issue, I will be working on it

Sure, 

I am assigning you this issue.
