### ISSUE TITLE
[FEATURE] Create Events page (same like blogs)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#12]
### Detailed description

We have to build an event page like this
<img alt="drawing" width="200" src="https://user-images.githubusercontent.com/44284877/194090481-fa39118b-b2fd-48be-8ffb-096f4e3c67c4.png">

### Context

Website: https://www.thecyberhub.org/events
React Sourcecode: https://github.com/thecyberworld/thecyberhub.org

### Possible implementation

If you need any help or have any doubts, let us know below.

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thilagavathi1** [comment]
@kabir0x23 could assign this issue to me. i will work on it

**Comment by Thilagavathi1** [comment]
@kabir0x23 when this events screen will appear.
if possible share the navigation screen names to reach events screen

**Comment by kabir0x23** [comment]
> @kabir0x23 when this events screen will appear?
> if possible share the navigation screen names to reach events screen.currently there is 3 tabs.
> 

Yes you can create a new screen or remove any, this is on your preference.

We will later restructured the navigations.

**Comment by Thilagavathi1** [comment]
ok got it . Thanks for the info

**Comment by Thilagavathi1** [comment]
@kabir0x23 raised an [PR](https://github.com/thecyberworld/thecyberhub-app/pull/19)
