### ISSUE TITLE
[FEATURE] Build simple quizz app

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#13]
### Detailed description

We have to build a simple quiz app in react-native.

Example: 

<img alt="drawing" width="300" src="https://user-images.githubusercontent.com/44284877/194100041-535295ea-ca6d-4784-99f7-245dfa92b4f8.png">

### Context

React SourceCode: https://github.com/thecyberworld/thecyberhub.org
Website link: https://thecyberhub.org/prep/quiz

### Possible implementation

If you need any help or have any doubts, ley us know.

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
> @kabir0x23 assign this issue to me i will work on it

Okay.

I an assigning this issueto you.

**Comment by ArkadiK94** [comment]
Is this issue still relevant? If so, assign me. I would like to handle it under the hacktoberfest event.

**Comment by kabir0x23** [comment]
> Is this issue still relevant? If so, assign me. I would like to handle it under the hacktoberfest event.

Hey, u have checkedTheCyberHUB website


So we are making it's app too 

So we have to add all the things those are in thecyberhub.org to this Android app..

The quiz feature reference you can get from the website, we have to make the same things

Also you can create more issues.. checkout TheCyberHub.org and on the basis of that u can create for this app

Thank you

**Comment by ArkadiK94** [comment]
Ok, I get it, first I would like to work on this feature.
Note: I will be able to test/watch it only on Android. Is it ok? (I don't have an iOS device) If it is fine, please assign me to this issue.

**Comment by kabir0x23** [comment]
> Ok, I get it, first I would like to work on this feature. Note: I will be able to test/watch it only on Android. Is it ok? (I don't have an iOS device) If it is fine, please assign me to this issue.

yeah as of now, we are also focusing on androind

first try to run the app, i think, it is giving lots of errors.

**Comment by ArkadiK94** [comment]
> > Ok, I get it, first I would like to work on this feature. Note: I will be able to test/watch it only on Android. Is it ok? (I don't have an iOS device) If it is fine, please assign me to this issue.
> 
> yeah as of now, we are also focusing on androind
> 
> first try to run the app, i think, it is giving lots of errors.

Yes, it was. I fixed them. There was not a big issues so I hope it is ok that I created one pr for all the problems that I noticed.

**Comment by kabir0x23** [comment]
> > > Ok, I get it, first I would like to work on this feature. Note: I will be able to test/watch it only on Android. Is it ok? (I don't have an iOS device) If it is fine, please assign me to this issue.
> > 
> > yeah as of now, we are also focusing on androind
> > 
> > first try to run the app, i think, it is giving lots of errors.
> 
> Yes, it was. I fixed them. There was not a big issues so I hope it is ok that I created one pr for all the problems that I noticed. 

Okay, yeah we don't have any issues with that

Thanks for your contributions

**Comment by ArkadiK94** [comment]
@kabir0x23 Hi, I am still want to work on this issue, but first, I am waiting the #81 pr to be completed because it affects every file and there will be a lot of conflicts of I will start to do this feature now.
