### ISSUE TITLE
[BUG] Taking time to load background image/video

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#16]
### Describe the bug

When the app launches it takes time to load the the background image
Like somewhat 1-2 sec. (after splashscreen)

<img src="https://user-images.githubusercontent.com/44284877/194132075-6b469c6c-18f0-4385-a16d-fba43a3047d6.jpg" alt="image" width="200"/>
<img src="https://user-images.githubusercontent.com/44284877/194132082-6a4118de-e27f-48ec-8e7d-592265154117.jpg" alt="image" width="200"/>

after that main screen loads 

### To Reproduce

open the app, wait and watch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
HeLLO @ATH42
Want to work on this issue?

**Comment by ATH42** [comment]
hey @kabir0x23 i might be able to work on this next weekend.

**Comment by kabir0x23** [comment]
> hey @kabir0x23 i might be able to work on this next weekend.

Okay great. 👍🏼

Remind me, when you will be available, I wil assign this issue to you.

Than you 😄.

**Comment by kabir0x23** [comment]
@ATH42 , i have a question
Are you in hacksquad?

**Comment by ATH42** [comment]
hey @kabir0x23 yes i am, was also in a team pretty high on the leaderboard, but i think my teammates got kicked or disqualified.

ps .: i will be able to work on this later tonight.

**Comment by kabir0x23** [comment]
> hey @kabir0x23 yes i am, was also in a team pretty high on the leaderboard, but i think my teammates got kicked or disqualified.
> 
> ps .: i will be able to work on this later tonight.

okay 💪🏽

**Comment by ArkadiK94** [comment]
@kabir0x23 Hi, I would like to work on it. Pls assign me.

**Comment by ArkadiK94** [comment]
Could you assign me to it, pls?

**Comment by kabir0x23** [comment]
> Could you assign me to it, pls?
u can start working on without getting assign, i will try to assign as soon possible but the doestn metter as of now
u can work on any issue, there is no need to be assigned for working, as of now uu are the only one working on this project 😄

thank you
