### ISSUE TITLE
[FEATURE] add simple Homepage

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#2]
Thecyberhub-app is a react-native app

We have to build the same home page

Here is our home screen:
![photo_2022-10-04_00-06-58](https://user-images.githubusercontent.com/44284877/193653138-6cc2731c-5ee7-414f-91b9-661cb554a8c2.jpg)

and we want to this exactly same on our home screen
![image](https://user-images.githubusercontent.com/44284877/193653276-e382f479-a520-4bab-a38f-fed2f153a05f.png)

website link https://www.thecyberhub.org/
website source code is also available on the GitHub

If you need any help or having doubts, let us know:

Thanks

**Comment by thisisharsh7** [comment]
I would like to work on this issue. could you please assign it to me?

**Comment by ATH42** [comment]
ill take this up

**Comment by kabir0x23** [comment]
> ill take this up. 
> the Hamburger menu seems unnecessary on mobile. 
> since you already have a tab navigator on the bottom.

Hey @ATH42 

Yes we don't have to implement Hamburger

Sure, I am assigning you this issue.

If you will have any questions or doubts, let us know below

Thanks.

**Comment by kabir0x23** [comment]
If you want to make bottom-navbar with your own style, you can make
And can restructured the components and names.

**Comment by ATH42** [comment]
could you refer me to the background image that you used on the web page?

should i also add the cyberworld logo as a splashscreen?

**Comment by kabir0x23** [comment]
> could you refer me to the background image that you used on the web page?
> 
> should i also add the cyberworld logo as a splashscreen?

Splashscreen, great, yes you can use thecyberworld logo as splashscreen

And about background image
We are using a video in a background.
