### ISSUE TITLE
[FEATURE] Community page (separate page)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#20]
### Detailed description

We have to build a community page.

- A little bit about community 
- Discord link

This is a react native project
We have to make the same page like this on this project

### Context

The community page will help user to know more about the community 
and will be able to join the community through the community page.

### Possible implementation

Example page: 
![image](https://user-images.githubusercontent.com/44284877/195840921-11483f23-3516-4e3c-aead-ebe992362287.png)

### Additional information

If you need any help or have any doubts, can ask below.
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanketshevare** [comment]
Hey can you assign this issue to me? 😁

**Comment by kabir0x23** [comment]
Great, I am assigning this issue to you.

**Comment by sanketshevare** [comment]
Thank you

**Comment by sanketshevare** [comment]
We will create community page same as website and we can add the project section into community page is this okay?

**Comment by kabir0x23** [comment]
> We will create community page same as website and we can add the project section into community page is this okay?

in the community page, we can add github and other links

**Comment by sanketshevare** [comment]
Okay i will work on this

**Comment by sanketshevare** [comment]
Hey @kabir0x23  take a look at this 
![Screenshot_2022-10-21-17-06-48-15_f73b71075b1de7323614b647fe394240.jpg](https://user-images.githubusercontent.com/69853783/197187272-4bba3c76-99aa-4539-acf0-00c075f7a852.jpg)

**Comment by kabir0x23** [comment]
this looks awesome

suggestions:
- can you change the color of the background of the discord button

**Comment by sanketshevare** [comment]
Yes sure

**Comment by sanketshevare** [comment]
Do u have any recommendations for that?

**Comment by sanketshevare** [comment]
Hey @kabir0x23 merge the new changes in community page and I'll add the animation and other part by later on

**Comment by sanketshevare** [comment]
Is this okay?


![Screenshot_2022-10-22-18-24-53-28_f73b71075b1de7323614b647fe394240.jpg](https://user-images.githubusercontent.com/69853783/197340130-8e9258da-0fe1-400a-a734-1047828468c9.jpg)

**Comment by kabir0x23** [comment]
Awesome, loved this

**Comment by kabir0x23** [comment]
Great, we will review your PR and merge very soon. until then/If you are looking to contribute more to the open-source, then you can give a look at other open issues or can create issues.

Thank you 😄.

**Comment by sanketshevare** [comment]
Thanks
