### ISSUE TITLE
[FEATURE] Jobs/Internships page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#21]
### Detailed description

For example, what we trying to build:
<img src="https://user-images.githubusercontent.com/44284877/193441392-ea8f3663-e779-492c-b89e-53d627d7f144.png" alt="drawing" width="350"/>

This is a react native project
We have to make the same page like this on this project

### Context

The jobs page will be going to help community members and other users 

### Possible implementation

tech-stack: react and styled-components or CSS

### Additional information

If you need any help or have any doubts, let us know.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by logicalahara** [comment]
Hey @kabir0x23, I got a good grip over react-native and would love to contribute to this.

#### Can you please assign this to me ?

**Comment by logicalahara** [comment]
@kabir0x23, for the job card, we utilise static data or fetch it over some API ?

**Comment by kabir0x23** [comment]
> @kabir0x23, for the job card, we utilise static data or fetch it over some API ?

right now dummy data.
we will add database lateron

**Comment by kabir0x23** [comment]
> @kabir0x23, for the job card, we utilise static data or fetch it over some API ?

Awesome, i am assigning this issue to you

**Comment by logicalahara** [comment]
@kabir0x23 any specifics to contributing_guide ?

**Comment by logicalahara** [comment]
@kabir0x23 do we need to create a new bottom tab `Jobs` ?

**Comment by kabir0x23** [comment]
> @kabir0x23 do we need to create a new bottom tab `Jobs` ? please provide clarity for the same

Yes you can create a new button at bottom

**Comment by kabir0x23** [comment]
> @kabir0x23 any specifics to contributing guide?

this is the react contributing guide, 
its similar with react-native other than the installtion steps:
https://github.com/thecyberworld/thecyberhub.org/blob/main/CONTRIBUTING.md

**Comment by kabir0x23** [comment]
Hey

**Comment by kabir0x23** [comment]
Here is the website, we are making an app for this website:

https://github.com/thecyberworld/thecyberhub.org

here we already have to code and desing for the Jobs page

PR we are going to merge soon and then you can lookout at the desing and at the code
you also can improve the design....
![image](https://user-images.githubusercontent.com/44284877/196037922-2e32837c-a0fb-47a4-9143-ae366e9e3a65.png)

Thanks.

**Comment by logicalahara** [comment]
@kabir0x23 can we use 3rd party UI component libs or stick around using react-native components ?

**Comment by kabir0x23** [comment]
> @kabir0x23 can we use 3rd party UI component libs or stick around using react-native components ?

we don't like to use 3rd party UI libs, yes you have to stick around using react-native components

Thanks

**Comment by logicalahara** [comment]
@kabir0x23 Please review PR https://github.com/thecyberworld/thecyberhub-app/pull/42

**Comment by logicalahara** [comment]
request you to please close this PR as today is last day of hacktoberfest

**Comment by kabir0x23** [comment]
> request you to please close this PR as today is last day of hacktoberfest

Awesome, will review and merge in a hr 

Thank you

**Comment by logicalahara** [comment]
@kabir0x23 any progress on this ?
