### ISSUE TITLE
[FEATURE] Add courses page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub-app#22]
### Detailed description

example link: https://www.thecyberhub.org/resources/courses
### Context

This is a react native project
We have to make the same page like this

![image](https://user-images.githubusercontent.com/44284877/195841689-fb7c4a5a-d901-4b43-83c2-0039dbc1fd0f.png)

sourcecode: https://github.com/thecyberworld/thecyberhub.org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Divyesh1511** [comment]
Hey, can you please elaborate on what to do with it, like course page is already there on the website so.

**Comment by kabir0x23** [comment]
> Hey, can you please elaborate on what to do with it, like course page is already there on the website so.

this is a react-native project,

**Comment by sanketshevare** [comment]
can i look into this?

**Comment by sanketshevare** [comment]
Thank you!
I already done this is this ok?
![Screenshot from 2022-10-19 19-01-36](https://user-images.githubusercontent.com/69853783/196705787-84ed9a09-3a32-49b2-84df-a33a5fe26a91.png)

**Comment by kabir0x23** [comment]
> Thank you! I already done this is this ok? ![Screenshot from 2022-10-19 19-01-36](https://user-images.githubusercontent.com/69853783/196705787-84ed9a09-3a32-49b2-84df-a33a5fe26a91.png)

yes somewhat
but we have to make the card different from the events:
components and CSS of courses card has already given

**Comment by sanketshevare** [comment]
Ok i'll make it and this courses styles are same as website right?

**Comment by kabir0x23** [comment]
> Ok i'll make it and this courses styles are same as website right?

yeah and you can find the CSS components from here.

**Comment by sanketshevare** [comment]
Ok thank you!

**Comment by sanketshevare** [comment]
Can you assign this issue to me ?

**Comment by kabir0x23** [comment]
> Can you assign this issue to me ?

already assigned 
![image](https://user-images.githubusercontent.com/44284877/196756669-b7d7ec01-1b22-4f36-9f16-c840aa6b2b8f.png)

**Comment by sanketshevare** [comment]
Thanks 👍

**Comment by sanketshevare** [comment]
Hey @kabir0x23 I have done this like on website and if user clock on upper image it will go to youtube video and for lower image it will go to youtube channel is this okay? And if there are any changes let me know
 ![Screenshot_2022-10-20-18-46-42-35_f73b71075b1de7323614b647fe394240.jpg](https://user-images.githubusercontent.com/69853783/196959242-bafa0958-0590-449b-8b45-a337d710d6d6.jpg)

**Comment by sanketshevare** [comment]
Hey @kabir0x23 I have done this like on website and if user clock on upper image it will go to youtube video and for lower image it will go to youtube channel is this okay? And if there are any changes let me know

![Screenshot_2022-10-20-18-52-46-96_f73b71075b1de7323614b647fe394240.jpg](https://user-images.githubusercontent.com/69853783/196960496-338538ed-95b8-4d74-b7bb-667ac1f04c5d.jpg)

**Comment by kabir0x23** [comment]
Awesome
 
And for some changes:
- You can include the image and title in the youtube video link
- Channel image and name under channel link.

**Comment by sanketshevare** [comment]
Yes that's already done ✅

**Comment by kabir0x23** [comment]
> Yes that's already done ✅

Super 🔥

**Comment by sanketshevare** [comment]
Can you review the pull request it has a conflict?

**Comment by kabir0x23** [comment]
Great, we will review your PR and merge very soon. until then/If you are looking to contribute more to the open-source, then you can give a look at other open issues or can create issues.

Thank you 😄.

**Comment by sanketshevare** [comment]
Okay 😀

**Comment by sanketshevare** [comment]
Do you have any design ideas about settings page?

**Comment by kabir0x23** [comment]
> Do you have any design ideas about settings page?

Yeah, something like:
- dark mode on/off
- versions

What we can add more?

**Comment by sanketshevare** [comment]
Like feedback section and help section

**Comment by sanketshevare** [comment]
Hey @kabir0x23  can you assign settings page issue (feature) to me?
