### ISSUE TITLE
Settings page 

### ISSUE THREAD

**Issue by sanketshevare** [thecyberworld/thecyberhub-app#37]
### Detailed description

Settings page containing dark mode switch, feedback and help section 

### Context

Settings page containing dark mode switch, feedback and help section

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sanketshevare** [comment]
![Screenshot_2022-10-28-13-11-22-14_f73b71075b1de7323614b647fe394240.jpg](https://user-images.githubusercontent.com/69853783/198532040-ff2da0b3-3999-4ec6-a72d-c0483e02fe32.jpg)

**Comment by logicalahara** [comment]
@kabir0x23 should I continue working on this ? Please assign this to me and add 'hacktoberfest' label to this issue.

**Comment by kabir0x23** [comment]
Awesome
