### ISSUE TITLE
[FEATURE] Add Splash Screen and App Logo

### ISSUE THREAD

**Issue by ATH42** [thecyberworld/thecyberhub-app#8]
### Detailed description

the App schould have a proper splash screen and logo added

### Context

basic setup

### Possible implementation

using the cyberworld logo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey @ATH42.

are you going to work on this issue?

**Comment by ATH42** [comment]
yes, i'll do it on a seperate branch.

but if there is anyone else that wants to take this, i am happy to leave it for them.

**Comment by kabir0x23** [comment]
> yes, i'll do it on a seperate branch.
> 
> but if there is anyone else that wants to take this, i am happy to leave it for them.

okay.
