### ISSUE TITLE
[FEATURE] Code Linting

### ISSUE THREAD

**Issue by ATH42** [thecyberworld/thecyberhub-app#9]
### Detailed description

The Codebase is pretty Raw at this point.
To make onboarding and contributing easier, lint rules and maybe a prettier setup are recommended

### Context

easiier to contribute.
no need for maintainers to force specific code styles in commentary -> can be handled by repo

### Possible implementation

esLint, Prettier

maybe tsconfig?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ATH42** [comment]
hey @kabir0x23 do you think this a good idea?

if yes i could set up some rules.

**Comment by kabir0x23** [comment]
> hey @kabir0x23 do you think this is a good idea?
> 
> if yes I could set up some rules.

Yes, this is a great idea.

I have also tried linting once on one of my project, linter and prettier on commit. 

Yes, go ahead 🚀.

**Comment by ATH42** [comment]
this is ready, but please merge #10 before this.

it would be recommended to maybe create another branch, to base feature branches off.

maybe: 

main for production ready
develop for developing and to base feature branches off?

**Comment by kabir0x23** [comment]
Okay nice,
Got it

Like
create a develop branch only for developing purposes.
and main for developing 

can you elaborate on, to base feature branches off?

**Comment by kabir0x23** [comment]
> this is ready, but please merge #10 before this.
> 
> it would be recommended to maybe create another branch, to base feature branches off.
> 
> maybe:
> 
> main for production-ready development for developing and to base feature branches off?

first merging PRs in dev branch (linters will their work)
and then we will merge it into the main branch

**Comment by ATH42** [comment]
exactly, the only branch that merges into master is develop all other branches go into develop first.

**Comment by kabir0x23** [comment]
> exactly, the only branch that merges into master is develop all other branches go into develop first.

Nice Nice

**Comment by kabir0x23** [comment]
> 
Okay got it.

**Comment by kabir0x23** [comment]
> exactly, the only branch that merges into master is develop all other branches go into develop first.
> 
> for example: checkout develop -> pull -> checkout -b some-feature -> PR to develop
> 
> I will add an action to check code in CI tomorrow, but you can still merge this, i will do all the actions on another branch.

I will a create a development branch
